language: groovy

jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - openjdk13

addons:
  apt:
    packages:
      - shellcheck

git:
  depth: 3000

addons:
  apt:
    packages:
      - graphviz

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./.ci.sh
  - find . -type f -exec grep -l '^#!/bin/bash' {} + | xargs shellcheck
